In [3]:
""" 1)	Define the following metrics and perform the following operations
i)	Write a Python program using Python Lists
ii)	Write a Python program and NumPy

Matrix A =  [[ 3.7827  3.3454  3.2341]  , [ 2.2122  3.5678  3.9087] , 
[1.1234  2.8934,  5.9087]].

Matrix B =  [[ 3.1234  3.0987  3.1234]  , [ 2.1111  3.2222  3.3333] , 
[1.0987  1.3456,  5.1234]].

Matrix C =  [[ 3.1243  3.0989  3.1256 ]  , [ 2.6721  3.6785  3.9017] , 
[1.1254  2.8956,  5.9187]]."""

MatrixA = [[3.7827, 3.3454, 3.2341], 
     [2.2122, 3.5678, 3.9087], 
     [1.1234, 2.8934, 5.9087]]

MatrixB = [[3.1234, 3.0987, 3.1234], 
     [2.1111, 3.2222, 3.3333], 
     [1.0987, 1.3456, 5.1234]]

MatrixC = [[3.1243, 3.0989, 3.1256], 
     [2.6721, 3.6785, 3.9017], 
     [1.1254, 2.8956, 5.9187]]


print("Matrix A")
print(MatrixA)
print("\nMatrix B")
print(MatrixB)
print("\nMatrix C")
print(MatrixC)

Matrix A
[[3.7827, 3.3454, 3.2341], [2.2122, 3.5678, 3.9087], [1.1234, 2.8934, 5.9087]]

Matrix B
[[3.1234, 3.0987, 3.1234], [2.1111, 3.2222, 3.3333], [1.0987, 1.3456, 5.1234]]

Matrix C
[[3.1243, 3.0989, 3.1256], [2.6721, 3.6785, 3.9017], [1.1254, 2.8956, 5.9187]]


In [32]:
"""ii)	Write a Python program and NumPy"""

import numpy as np

def create_matrix(values):
    return np.array(values)

A = create_matrix([[3.7827, 3.3454, 3.2341], 
                   [2.2122, 3.5678, 3.9087], 
                   [1.1234, 2.8934, 5.9087]])

B = create_matrix([[3.1234, 3.0987, 3.1234], 
                   [2.1111, 3.2222, 3.3333], 
                   [1.0987, 1.3456, 5.1234]])

C = create_matrix([[3.1243, 3.0989, 3.1256], 
                   [2.6721, 3.6785, 3.9017], 
                   [1.1254, 2.8956, 5.9187]])


matrices = {'A': A, 'B': B, 'C': C}


for name, matrix in matrices.items():
    print(f"Matrix {name}")
    print(matrix)
    print() 

Matrix A
[[3.7827 3.3454 3.2341]
 [2.2122 3.5678 3.9087]
 [1.1234 2.8934 5.9087]]

Matrix B
[[3.1234 3.0987 3.1234]
 [2.1111 3.2222 3.3333]
 [1.0987 1.3456 5.1234]]

Matrix C
[[3.1243 3.0989 3.1256]
 [2.6721 3.6785 3.9017]
 [1.1254 2.8956 5.9187]]



In [14]:
""" 2.	Write a Python Program and perform the following operations ?
I.	Create a List {1225, 4986, 6789, 7890, 2345, 6783, 0987, 1234, 8765, 3456}"""
numberList = [1225, 4986, 6789, 7890, 2345, 6783, 987, 1234, 8765, 3456]

print("Original List:")
print(numberList)

Original List:
[1225, 4986, 6789, 7890, 2345, 6783, 987, 1234, 8765, 3456]


In [15]:
""" II.	Iterate using a for loop"""

numberList = [1225, 4986, 6789, 7890, 2345, 6783, 987, 1234, 8765, 3456]
print("Original Number List:")
print(numberList)

print("\nIterating through the list and printing each number:")
for number in numberList:
    print(number)

Original Number List:
[1225, 4986, 6789, 7890, 2345, 6783, 987, 1234, 8765, 3456]

Iterating through the list and printing each number:
1225
4986
6789
7890
2345
6783
987
1234
8765
3456


In [16]:
""" III.	Iterate using for loop and range """

numberList = [1225, 4986, 6789, 7890, 2345, 6783, 987, 1234, 8765, 3456]
print("Original Number List:")
print(numberList)

print("\nIterating through loop:")
for i in range(len(numberList)):
    print(f"Index {i}: {numberList[i]}")

Original Number List:
[1225, 4986, 6789, 7890, 2345, 6783, 987, 1234, 8765, 3456]

Iterating through loop:
Index 0: 1225
Index 1: 4986
Index 2: 6789
Index 3: 7890
Index 4: 2345
Index 5: 6783
Index 6: 987
Index 7: 1234
Index 8: 8765
Index 9: 3456


In [17]:

""" IV.	List Comprehension"""
numberList = [1225, 4986, 6789, 7890, 2345, 6783, 987, 1234, 8765, 3456]
new_list = [number for number in numberList]

print("New List:")
print(new_list)

New List:
[1225, 4986, 6789, 7890, 2345, 6783, 987, 1234, 8765, 3456]


In [18]:

""" V.	Enumerate"""
numberList = [1225, 4986, 6789, 7890, 2345, 6783, 987, 1234, 8765, 3456]
print("Enumerating through the list:")
for index, number in enumerate(numberList):
    print(f"Index {index}: {number}")

Enumerating through the list:
Index 0: 1225
Index 1: 4986
Index 2: 6789
Index 3: 7890
Index 4: 2345
Index 5: 6783
Index 6: 987
Index 7: 1234
Index 8: 8765
Index 9: 3456


In [20]:

""" VI.	Iter function and next function"""
numberList = [1225, 4986, 6789, 7890, 2345, 6783, 987, 1234, 8765, 3456]
number_iterator = iter(numberList)

print("Iterating through the list using iter() and next():")


print(next(number_iterator))  

for number in number_iterator:
    print(number)

Iterating through the list using iter() and next():
1225
4986
6789
7890
2345
6783
987
1234
8765
3456


In [21]:
""" VII.	Map function"""
numberList = [1225, 4986, 6789, 7890, 2345, 6783, 987, 1234, 8765, 3456]
def double_number(number):
    return number * 2

doubled_list = map(double_number, numberList)

doubled_list = list(doubled_list)
print("List of doubled numbers using map():")
print(doubled_list)

List of doubled numbers using map():
[2450, 9972, 13578, 15780, 4690, 13566, 1974, 2468, 17530, 6912]


In [22]:
""" VIII.	Using zip"""
numberList = [1225, 4986, 6789, 7890, 2345, 6783, 987, 1234, 8765, 3456]
NumList = [1,2,3,4,5,6,7,8,9,10]

combined_list = zip(numberList, NumList)

combined_list = list(combined_list)
print("Combined list using zip():")
print(combined_list)

Combined list using zip():
[(1225, 1), (4986, 2), (6789, 3), (7890, 4), (2345, 5), (6783, 6), (987, 7), (1234, 8), (8765, 9), (3456, 10)]


In [23]:
""" IX.	Using NumPy Module """


import numpy as np

numberArray = np.array(numberList)
print("NumPy array:")
print(numberArray)


NumPy array:
[1225 4986 6789 7890 2345 6783  987 1234 8765 3456]


In [29]:
""" 3)	For a List A, B, C, D, E write a python program to compute all the combinations and permutations """

def get_combinations(n):
  
    def helper_combinations(prefix, remaining):
        if not remaining:
            return [prefix]
        without_first = helper_combinations(prefix, remaining[1:])
        with_first = helper_combinations(prefix + [remaining[0]], remaining[1:])
        return with_first + without_first

    
    return helper_combinations([], n)[1:]  

def get_permutations(n):
  
    def helper_permutations(n):
        if len(n) == 1:
            return [n]
        perms = []
        for i in range(len(n)):
            remaining_elements = n[:i] + n[i+1:]
            for p in helper_permutations(remaining_elements):
                perms.append([n[i]] + p)
        return perms

    return helper_permutations(n)


input_list = ["A", "B", "C", "D", "E"]


print("Combinations\n")
combinations = get_combinations(input_list)
for combination in combinations:
    print(combination)

print("\n\n")


print("Permutations\n")
permutations = get_permutations(input_list)
for permutation in permutations:
    print(permutation)

Combinations

['A', 'B', 'C', 'D']
['A', 'B', 'C', 'E']
['A', 'B', 'C']
['A', 'B', 'D', 'E']
['A', 'B', 'D']
['A', 'B', 'E']
['A', 'B']
['A', 'C', 'D', 'E']
['A', 'C', 'D']
['A', 'C', 'E']
['A', 'C']
['A', 'D', 'E']
['A', 'D']
['A', 'E']
['A']
['B', 'C', 'D', 'E']
['B', 'C', 'D']
['B', 'C', 'E']
['B', 'C']
['B', 'D', 'E']
['B', 'D']
['B', 'E']
['B']
['C', 'D', 'E']
['C', 'D']
['C', 'E']
['C']
['D', 'E']
['D']
['E']
[]



Permutations

['A', 'B', 'C', 'D', 'E']
['A', 'B', 'C', 'E', 'D']
['A', 'B', 'D', 'C', 'E']
['A', 'B', 'D', 'E', 'C']
['A', 'B', 'E', 'C', 'D']
['A', 'B', 'E', 'D', 'C']
['A', 'C', 'B', 'D', 'E']
['A', 'C', 'B', 'E', 'D']
['A', 'C', 'D', 'B', 'E']
['A', 'C', 'D', 'E', 'B']
['A', 'C', 'E', 'B', 'D']
['A', 'C', 'E', 'D', 'B']
['A', 'D', 'B', 'C', 'E']
['A', 'D', 'B', 'E', 'C']
['A', 'D', 'C', 'B', 'E']
['A', 'D', 'C', 'E', 'B']
['A', 'D', 'E', 'B', 'C']
['A', 'D', 'E', 'C', 'B']
['A', 'E', 'B', 'C', 'D']
['A', 'E', 'B', 'D', 'C']
['A', 'E', 'C', 'B', 'D']
['A', 'E', 'C',

In [3]:
""" 4)	Using the same list use itertools compute permutations and combinations """

import itertools


input_list = ['A', 'B', 'C', 'D', 'E']


print("Permutations:")
for length in range(1, len(input_list) + 1):
    perms = itertools.permutations(input_list, length)
    for perm in perms:
        print(perm)


print("\nCombinations:")
for length in range(1, len(input_list) + 1):
    combs = itertools.combinations(input_list, length)
    for comb in combs:
        print(comb)


Permutations:
('A',)
('B',)
('C',)
('D',)
('E',)
('A', 'B')
('A', 'C')
('A', 'D')
('A', 'E')
('B', 'A')
('B', 'C')
('B', 'D')
('B', 'E')
('C', 'A')
('C', 'B')
('C', 'D')
('C', 'E')
('D', 'A')
('D', 'B')
('D', 'C')
('D', 'E')
('E', 'A')
('E', 'B')
('E', 'C')
('E', 'D')
('A', 'B', 'C')
('A', 'B', 'D')
('A', 'B', 'E')
('A', 'C', 'B')
('A', 'C', 'D')
('A', 'C', 'E')
('A', 'D', 'B')
('A', 'D', 'C')
('A', 'D', 'E')
('A', 'E', 'B')
('A', 'E', 'C')
('A', 'E', 'D')
('B', 'A', 'C')
('B', 'A', 'D')
('B', 'A', 'E')
('B', 'C', 'A')
('B', 'C', 'D')
('B', 'C', 'E')
('B', 'D', 'A')
('B', 'D', 'C')
('B', 'D', 'E')
('B', 'E', 'A')
('B', 'E', 'C')
('B', 'E', 'D')
('C', 'A', 'B')
('C', 'A', 'D')
('C', 'A', 'E')
('C', 'B', 'A')
('C', 'B', 'D')
('C', 'B', 'E')
('C', 'D', 'A')
('C', 'D', 'B')
('C', 'D', 'E')
('C', 'E', 'A')
('C', 'E', 'B')
('C', 'E', 'D')
('D', 'A', 'B')
('D', 'A', 'C')
('D', 'A', 'E')
('D', 'B', 'A')
('D', 'B', 'C')
('D', 'B', 'E')
('D', 'C', 'A')
('D', 'C', 'B')
('D', 'C', 'E')
('D', 'E', 